/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { t } from './i18n';
import { BuildingConfig, BuildingType, BuildingCategory, Milestone } from './types';

// Map Settings
export const GRID_SIZE = 50;
export const CHUNK_SIZE = 5;

// Game Settings
export const DAY_MS = 5000; // 1 in-game day = 5 real seconds
export const INITIAL_MONEY = 2500;

export const EconomyConfig = {
  passiveSubsidy: 15,
  taxPerPerson: 1.2,
  moveInBonus: 10,
  shopSmallIncome: 18,
  shopLargeIncome: 55,
  mallIncome: 180,
  financialCenterIncome: 750,
  factorySmallIncome: 35,
  factoryLargeIncome: 120,
  chemicalPlantIncome: 420,
  highTechFactoryIncome: 1800,
  levelIncomeMultiplier: 0.05, // +5% per level
};

export const MILESTONES: Milestone[] = [
  { level: 1, get name() { return t('m_lvl1'); },requiredPop: 0 },
  { level: 2, get name() { return t('m_lvl2'); },requiredPop: 40 },
  { level: 3, get name() { return t('m_lvl3'); },requiredPop: 120 },
  { level: 4, get name() { return t('m_lvl4'); },requiredPop: 400 },
  { level: 5, get name() { return t('m_lvl5'); },requiredPop: 1000 },
  { level: 6, get name() { return t('m_lvl6'); },requiredPop: 2200 },
  { level: 7, get name() { return t('m_lvl7'); },requiredPop: 5000 },
  { level: 8, get name() { return t('m_lvl8'); },requiredPop: 8500 },
];

export const BUILDINGS: Record<BuildingType, BuildingConfig> = {
  [BuildingType.None]: {
    type: BuildingType.None,
    category: BuildingCategory.Infrastructure,
    cost: 25, // Снос
    get name() { return t('b_none_name'); },
    get description() { return t('b_none_desc'); },
    color: '#ef4444',
    popGen: 0,
    incomeGen: 0,
    minLevel: 1,
    width: 1, height: 1,
  },
  [BuildingType.BuyLand]: {
    type: BuildingType.BuyLand,
    category: BuildingCategory.Infrastructure,
    cost: 500, // Базовая стоимость, будет увеличиваться программно
    get name() { return t('b_buyland_name'); },
    get description() { return t('b_buyland_desc'); },
    color: '#22c55e',
    popGen: 0,
    incomeGen: 0,
    minLevel: 1,
    width: 1, height: 1,
  },
  [BuildingType.Road]: {
    type: BuildingType.Road,
    category: BuildingCategory.Infrastructure,
    cost: 50,
    get name() { return t('b_road_name'); },
    get description() { return t('b_road_desc'); },
    color: '#374151',
    popGen: 0,
    incomeGen: 0,
    minLevel: 1,
    width: 1, height: 1,
  },
  [BuildingType.HouseSmall]: {
    type: BuildingType.HouseSmall,
    category: BuildingCategory.Residential,
    cost: 50,
    get name() { return t('b_house_small_name'); },
    get description() { return t('b_house_small_desc'); },
    color: '#f87171',
    popGen: 1,
    incomeGen: 0,
    minLevel: 1,
    width: 1, height: 1,
  },
  [BuildingType.HouseMedium]: {
    type: BuildingType.HouseMedium,
    category: BuildingCategory.Residential,
    cost: 150,
    get name() { return t('b_house_medium_name'); },
    get description() { return t('b_house_medium_desc'); },
    color: '#ef4444',
    popGen: 3,
    incomeGen: 0,
    minLevel: 2,
    width: 1, height: 2,
  },
  [BuildingType.HouseLarge]: {
    type: BuildingType.HouseLarge,
    category: BuildingCategory.Residential,
    cost: 600,
    get name() { return t('b_house_large_name'); },
    get description() { return t('b_house_large_desc'); },
    color: '#b91c1c',
    popGen: 6,
    incomeGen: 0,
    minLevel: 3,
    width: 2, height: 2,
  },
  [BuildingType.ShopSmall]: {
    type: BuildingType.ShopSmall,
    category: BuildingCategory.Commercial,
    cost: 100,
    get name() { return t('b_shop_small_name'); },
    get description() { return t('b_shop_small_desc', {income: EconomyConfig.shopSmallIncome}); },
    color: '#60a5fa',
    popGen: 0,
    incomeGen: EconomyConfig.shopSmallIncome,
    minLevel: 1,
    width: 2, height: 2,
  },
  [BuildingType.ShopLarge]: {
    type: BuildingType.ShopLarge,
    category: BuildingCategory.Commercial,
    cost: 1000,
    get name() { return t('b_shop_large_name'); },
    get description() { return t('b_shop_large_desc', {income: EconomyConfig.shopLargeIncome}); },
    color: '#2563eb',
    popGen: 0,
    incomeGen: EconomyConfig.shopLargeIncome,
    minLevel: 3,
    width: 2, height: 3,
  },
  [BuildingType.Mall]: {
    type: BuildingType.Mall,
    category: BuildingCategory.Commercial,
    cost: 8000,
    get name() { return t('b_mall_name'); },
    get description() { return t('b_mall_desc', {income: EconomyConfig.mallIncome}); },
    color: '#1d4ed8',
    popGen: 0,
    incomeGen: EconomyConfig.mallIncome,
    minLevel: 5,
    width: 3, height: 3,
  },
  [BuildingType.FinancialCenter]: {
    type: BuildingType.FinancialCenter,
    category: BuildingCategory.Commercial,
    cost: 40000,
    get name() { return t('b_fin_center_name'); },
    get description() { return t('b_fin_center_desc', {income: EconomyConfig.financialCenterIncome}); },
    color: '#1e3a8a',
    popGen: 0,
    incomeGen: EconomyConfig.financialCenterIncome,
    minLevel: 8,
    width: 3, height: 4,
  },
  [BuildingType.FactorySmall]: {
    type: BuildingType.FactorySmall,
    category: BuildingCategory.Industrial,
    cost: 200,
    get name() { return t('b_factory_small_name'); },
    get description() { return t('b_factory_small_desc', {income: EconomyConfig.factorySmallIncome}); },
    color: '#facc15',
    popGen: 0,
    incomeGen: EconomyConfig.factorySmallIncome,
    minLevel: 1,
    width: 2, height: 2,
  },
  [BuildingType.FactoryLarge]: {
    type: BuildingType.FactoryLarge,
    category: BuildingCategory.Industrial,
    cost: 2000,
    get name() { return t('b_factory_large_name'); },
    get description() { return t('b_factory_large_desc', {income: EconomyConfig.factoryLargeIncome}); },
    color: '#b45309',
    popGen: 0,
    incomeGen: EconomyConfig.factoryLargeIncome,
    minLevel: 4,
    width: 2, height: 3,
  },
  [BuildingType.ChemicalPlant]: {
    type: BuildingType.ChemicalPlant,
    category: BuildingCategory.Industrial,
    cost: 15000,
    get name() { return t('b_chem_plant_name'); },
    get description() { return t('b_chem_plant_desc', {income: EconomyConfig.chemicalPlantIncome}); },
    color: '#78350f',
    popGen: 0,
    incomeGen: EconomyConfig.chemicalPlantIncome,
    minLevel: 5,
    width: 3, height: 3,
  },
  [BuildingType.HighTechFactory]: {
    type: BuildingType.HighTechFactory,
    category: BuildingCategory.Industrial,
    cost: 80000,
    get name() { return t('b_high_tech_name'); },
    get description() { return t('b_high_tech_desc', {income: EconomyConfig.highTechFactoryIncome}); },
    color: '#451a03',
    popGen: 0,
    incomeGen: EconomyConfig.highTechFactoryIncome,
    minLevel: 8,
    width: 4, height: 4,
  },
  [BuildingType.ParkSmall]: {
    type: BuildingType.ParkSmall,
    category: BuildingCategory.Decorations,
    cost: 100,
    get name() { return t('b_park_small_name'); },
    get description() { return t('b_park_small_desc'); },
    color: '#4ade80',
    popGen: 0,
    incomeGen: 0,
    minLevel: 1,
    width: 1, height: 1,
  },
  [BuildingType.ParkLarge]: {
    type: BuildingType.ParkLarge,
    category: BuildingCategory.Decorations,
    cost: 800,
    get name() { return t('b_park_large_name'); },
    get description() { return t('b_park_large_desc'); },
    color: '#16a34a',
    popGen: 0,
    incomeGen: 0,
    minLevel: 3,
    width: 2, height: 2,
  },
  [BuildingType.AquaPark]: {
    type: BuildingType.AquaPark,
    category: BuildingCategory.Decorations,
    cost: 5000,
    get name() { return t('b_aqua_park_name'); },
    get description() { return t('b_aqua_park_desc'); },
    color: '#22d3ee',
    popGen: 0,
    incomeGen: 0,
    minLevel: 5,
    width: 3, height: 3,
  },
  [BuildingType.AmusementPark]: {
    type: BuildingType.AmusementPark,
    category: BuildingCategory.Decorations,
    cost: 20000,
    get name() { return t('b_amuse_park_name'); },
    get description() { return t('b_amuse_park_desc'); },
    color: '#ec4899',
    popGen: 0,
    incomeGen: 0,
    minLevel: 7,
    width: 4, height: 4,
  },
};
